# Extra source files for the generated CCS makefile.
OBJS += oled/oled.o
ORDERED_OBJS := "oled/oled.o" $(ORDERED_OBJS)

oled/oled.o: ../oled/oled.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES) oled
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"$(CG_TOOL_ROOT)/bin/tiarmclang.exe" -c -march=thumbv6m -mcpu=cortex-m0plus -mfloat-abi=soft -mlittle-endian -mthumb -O2 -I"D:/AiliuCheng/work/DIAN_RACE/aa/car" -I"D:/AiliuCheng/work/DIAN_RACE/aa/car/Debug" -I"D:/AiliuCheng/work/DIAN_RACE/TiSDK/mspm0_sdk_2_10_00_04/source/third_party/CMSIS/Core/Include" -I"D:/AiliuCheng/work/DIAN_RACE/TiSDK/mspm0_sdk_2_10_00_04/kernel/freertos/Source/include" -I"D:/AiliuCheng/work/DIAN_RACE/TiSDK/mspm0_sdk_2_10_00_04/source" -I"D:/AiliuCheng/work/DIAN_RACE/TiSDK/mspm0_sdk_2_10_00_04/kernel/freertos/Source/portable/TI_ARM_CLANG/ARM_CM0" -I"D:/AiliuCheng/work/DIAN_RACE/TiSDK/mspm0_sdk_2_10_00_04/source/ti/posix/ticlang" -I"D:/AiliuCheng/work/DIAN_RACE/aa/freertos_builds_LP_MSPM0G3507_release_ticlang" -I"D:/AiliuCheng/work/DIAN_RACE/aa/car/Driver" -I"D:/AiliuCheng/work/DIAN_RACE/aa/car/oled" -D__MSPM0G3507__ -gdwarf-3 -Wall -MMD -MP -MF"oled/oled.d_raw" -MT"$(@)" $(GEN_OPTS__FLAG) -o"$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

car.out: oled/oled.o

oled:
	-@if not exist "oled" mkdir "oled"
